# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMOLO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMOLO
pod 'Pulley'

pod 'FacebookCore'
pod 'FacebookLogin'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/AdMob'

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'ImageSlideshow/SDWebImage'

  target 'SMOLOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SMOLOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
