# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smolo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smolo
pod ‘Firebase/Core’
pod ‘Firebase’

  target 'SmoloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmoloUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
